In [1]:
from misvm import MISVM, miSVM, SIL
# from minet import MINet, miNet

In [2]:
from synthetic_datasets import *

In [3]:
xlabeled, y = create_mil_dataset_v2(np.random.randint(low=5, high=10, size=1200), prob_inst_pos=0.2, negative_label=-1)
x = remove_instance_level_labels(xlabeled)
train_x = x[:200]
train_y = y[:200]
valid_x = x[200:700]
valid_y = y[200:700]
test_x = x[700:]
test_y = y[700:]

In [35]:
MISVM_model = MISVM(max_iters=200, verbose=0)
MISVM_model.get_params()

{'C': 1.0,
 'gamma': 1.0,
 'kernel': 'linear',
 'max_iters': 200,
 'p': 3,
 'restarts': 0,
 'scale_C': True,
 'sv_cutoff': 1e-07,
 'verbose': 0}

In [5]:
SIL_model = SIL(verbose=0)
SIL_model.get_params()

{'C': 1.0,
 'gamma': 1.0,
 'kernel': 'linear',
 'p': 3,
 'scale_C': True,
 'sv_cutoff': 1e-07,
 'verbose': 0}

In [36]:
svm_grid = [
{
    'C': [0.001, 0.01, 0.1, 1.],
    'kernel': ['linear', 'quadratic'],
    'restarts': [2],
    'scale_C': [True, False],
#     'max_iters': [500],
},
{
    'C': [0.001, 0.01, 0.1, 1.],
    'kernel': ['rbf'],
    'gamma': [0.001, 0.01, 0.1, 1.],
    'restarts': [2],
    'scale_C': [True, False],
#     'max_iters': [500],
}]

In [37]:
MISVM_model.fit(train_x, train_y)

In [6]:
SIL_model.fit(train_x, train_y)

In [38]:
# %%debug
MISVM_model.predict(train_x)

array([-0.18372087, -0.06223569,  0.05512764, -0.11219443,  0.11444124,
       -0.00823105,  0.0247054 ,  0.51905237, -0.01847783, -0.28551827,
        0.03251914, -0.06173848,  0.02690454, -0.17102926, -0.19757327,
       -0.07049348,  0.18087989, -0.31251743, -0.22912573,  0.29414141,
       -0.14869442,  0.31950947,  0.32487919, -0.27719813, -0.35300037,
       -0.0026278 , -0.29393611,  0.12467022, -0.06834722, -0.21510696,
       -0.32829618,  0.2151396 , -0.15417026, -0.17814159,  0.03497033,
       -0.04405191, -0.16246148,  0.41405553, -0.13350074,  0.14885792,
        0.09623475, -0.10947091,  0.03168263, -0.11283201,  0.03421844,
       -0.0037241 ,  0.20905881,  0.13410458, -0.24922844,  0.28251072,
       -0.23271703, -0.12317121,  0.14799177,  0.1005308 ,  0.28940354,
        0.12245046, -0.35300061, -0.21337388, -0.19097391, -0.31789019,
       -0.2161255 ,  0.19720834,  0.33837675,  0.05837646, -0.30407218,
       -0.00502954, -0.29473215, -0.17574423, -0.0555017 ,  0.19

In [40]:
%%time
MISVM_results = run_mil_grid_search(MISVM_model, svm_grid, train_x, train_y, valid_x, valid_y, negative_label=-1)

Wall time: 2min 34s


In [41]:
MISVM_results[0]

MISVM(C=1.0, gamma=0.01, kernel='rbf', max_iters=200, p=3, restarts=2,
   scale_C=False, sv_cutoff=1e-07, verbose=0)

In [42]:
MISVM_results[1]

0.84799999999999998

In [43]:
np.mean(np.sign(MISVM_results[0].predict(test_x)) == test_y)

0.872

In [ ]:
np.

In [2]:
xlabeled, y = create_mil_dataset_v2([10]*1200, prob_inst_pos=0.2, negative_label=-1)

In [3]:
xlabeled

array([[[ 0.80912993,  0.17156252,  0.05606378, ..., -1.05319155,
         -1.15635552, -1.        ],
        [ 0.7721695 ,  0.03398174,  0.48338212, ...,  0.05645352,
          1.15513186, -1.        ],
        [-1.14881067, -0.6800621 , -2.64538148, ..., -0.38526892,
          1.17064813,  1.        ],
        ..., 
        [-0.71905095, -0.81014781,  0.04061312, ..., -0.502619  ,
         -1.33901975,  1.        ],
        [-1.62450753, -1.56340497,  0.17721902, ..., -0.32919743,
          0.38453473, -1.        ],
        [-0.85330294,  0.19205639, -1.50193138, ..., -0.37763849,
          0.32309   , -1.        ]],

       [[ 0.9091593 , -0.81443041,  0.1540751 , ..., -0.24606158,
         -0.56178004, -1.        ],
        [ 0.54784194, -0.42440175, -0.52473303, ...,  0.68365471,
         -1.48022935, -1.        ],
        [-1.57771441,  1.11038685,  1.17483606, ..., -1.47594698,
          1.16034178, -1.        ],
        ..., 
        [ 0.47287438, -0.72374042, -1.5728657 , ...,

In [12]:
xlabeled

array([[[ 0.80912993,  0.17156252,  0.05606378, ..., -1.05319155,
         -1.15635552, -1.        ],
        [ 0.7721695 ,  0.03398174,  0.48338212, ...,  0.05645352,
          1.15513186, -1.        ],
        [-1.14881067, -0.6800621 , -2.64538148, ..., -0.38526892,
          1.17064813,  1.        ],
        ..., 
        [-0.71905095, -0.81014781,  0.04061312, ..., -0.502619  ,
         -1.33901975,  1.        ],
        [-1.62450753, -1.56340497,  0.17721902, ..., -0.32919743,
          0.38453473, -1.        ],
        [-0.85330294,  0.19205639, -1.50193138, ..., -0.37763849,
          0.32309   , -1.        ]],

       [[ 0.9091593 , -0.81443041,  0.1540751 , ..., -0.24606158,
         -0.56178004, -1.        ],
        [ 0.54784194, -0.42440175, -0.52473303, ...,  0.68365471,
         -1.48022935, -1.        ],
        [-1.57771441,  1.11038685,  1.17483606, ..., -1.47594698,
          1.16034178, -1.        ],
        ..., 
        [ 0.47287438, -0.72374042, -1.5728657 , ...,